-- Seed data for Analytics Dashboard

-- Downtime records (last 30 days)
INSERT INTO downtime_records (line_name, reason, duration_minutes, occurred_at, notes) VALUES
  ('Juice Bottling Line A', 'machine_jam', 45, now() - interval '2 days', 'Conveyor belt jam resolved by maintenance'),
  ('Juice Bottling Line A', 'material_delay', 30, now() - interval '5 days', 'Waiting for bottle caps shipment'),
  ('Juice Bottling Line A', 'changeover', 60, now() - interval '8 days', 'Product changeover Mango to Pineapple'),
  ('Juice Bottling Line A', 'scheduled_maintenance', 120, now() - interval '12 days', 'Weekly maintenance cycle'),
  ('Dairy Packaged Foods Unit 1', 'equipment_failure', 90, now() - interval '3 days', 'Sealing head malfunction - replaced part'),
  ('Dairy Packaged Foods Unit 1', 'operator_break', 15, now() - interval '4 days', 'Shift changeover'),
  ('Dairy Packaged Foods Unit 1', 'quality_hold', 75, now() - interval '7 days', 'Quality inspection on batch B-102'),
  ('Dairy Packaged Foods Unit 1', 'material_delay', 45, now() - interval '10 days', 'Milk delivery delayed'),
  ('Pineapple Processing Line B', 'machine_jam', 35, now() - interval '1 day', 'Pulping machine blade jam'),
  ('Pineapple Processing Line B', 'power_outage', 25, now() - interval '6 days', 'Brief power fluctuation'),
  ('Pineapple Processing Line B', 'changeover', 50, now() - interval '9 days', 'Batch size changeover'),
  ('Mixed Fruit Beverage Line C', 'equipment_failure', 180, now() - interval '4 days', 'UHT pasteurizer heating element'),
  ('Mixed Fruit Beverage Line C', 'machine_jam', 20, now() - interval '11 days', 'Minor filler jam'),
  ('Mixed Fruit Beverage Line C', 'scheduled_maintenance', 90, now() - interval '15 days', 'Monthly deep clean'),
  ('Mango Juice Extraction Unit', 'material_delay', 40, now() - interval '2 days', 'Raw mango supply delayed'),
  ('Mango Juice Extraction Unit', 'machine_jam', 55, now() - interval '7 days', 'Extraction screw jam'),
  ('Mango Juice Extraction Unit', 'operator_break', 20, now() - interval '14 days', 'Lunch break rotation'),
  ('Water Bottling Line D', 'equipment_failure', 65, now() - interval '3 days', 'Pump pressure issue'),
  ('Water Bottling Line D', 'quality_hold', 30, now() - interval '8 days', 'pH adjustment needed'),
  ('Water Bottling Line D', 'changeover', 40, now() - interval '13 days', 'Bottle size changeover');

-- Fault records (last 14 days)
INSERT INTO fault_records (line_name, title, description, severity, category, logged_at, operator_name) VALUES
  ('Juice Bottling Line A', 'Conveyor belt sensor malfunction', 'Intermittent false stops detected on conveyor sensor #3', 'minor', 'sensor', now() - interval '1 day', 'Kato Peter'),
  ('Juice Bottling Line A', 'Filler nozzle drip', 'Filler head 4 showing drip after fill cycle', 'minor', 'equipment', now() - interval '3 days', 'Nakato Grace'),
  ('Juice Bottling Line A', 'Label printer misalignment', 'Labels printing 2mm offset from target position', 'minor', 'equipment', now() - interval '5 days', 'Auma Lydia'),
  ('Dairy Packaged Foods Unit 1', 'Temperature excursions in chiller', 'Chiller unit briefly hit 8°C during batch B-102', 'critical', 'quality', now() - interval '2 days', 'Wasswa Job'),
  ('Dairy Packaged Foods Unit 1', 'Seal integrity failure', '3 consecutive cups failed seal test on station 5', 'critical', 'quality', now() - interval '4 days', 'Okello David'),
  ('Dairy Packaged Foods Unit 1', 'Mixing paddle wear detected', 'Visual inspection shows paddle degradation', 'minor', 'equipment', now() - interval '7 days', 'Nankinga Sarah'),
  ('Pineapple Processing Line B', 'Pulping blade dullness', 'Reduced pulp yield on pineapple batch', 'minor', 'equipment', now() - interval '1 day', 'Ssentongo Mark'),
  ('Pineapple Processing Line B', 'Steam valve leak', 'Minor steam leak detected at pasteurizer inlet', 'critical', 'safety', now() - interval '6 days', 'Babirye Janet'),
  ('Mixed Fruit Beverage Line C', 'UHT temperature fluctuation', 'Temperature varied ±2°C during batch processing', 'critical', 'quality', now() - interval '2 days', 'Wasswa Job'),
  ('Mixed Fruit Beverage Line C', 'Homogenizer pressure drop', 'Pressure dropped below threshold during operation', 'critical', 'equipment', now() - interval '5 days', 'Nakato Grace'),
  ('Mixed Fruit Beverage Line C', 'Capping head misalignment', 'Caps not seating properly on 2% of bottles', 'minor', 'equipment', now() - interval '8 days', 'Okello David'),
  ('Mango Juice Extraction Unit', 'Extraction yield below target', 'Yield dropped to 82% vs 88% target', 'minor', 'process', now() - interval '3 days', 'Kato Peter'),
  ('Mango Juice Extraction Unit', 'Pump cavitation noise', 'Unusual noise from extraction pump bearing', 'minor', 'equipment', now() - interval '9 days', 'Nankinga Sarah'),
  ('Water Bottling Line D', 'Filter change overdue', 'Filter has exceeded recommended run hours', 'minor', 'maintenance', now() - interval '4 days', 'Auma Lydia'),
  ('Water Bottling Line D', 'Ozone level variance', 'Ozone dosing slightly below setpoint', 'minor', 'quality', now() - interval '10 days', 'Ssentongo Mark');

-- Scrap/waste records (last 30 days)
INSERT INTO scrap_records (line_name, product_type, ingredient_name, quantity_kg, reason, logged_at, logged_by) VALUES
  ('Juice Bottling Line A', 'Mango Juice', 'Fresh Mango Pulp', 45.5, 'QC rejection - Brix out of spec', now() - interval '2 days', gen_random_uuid()),
  ('Juice Bottling Line A', 'Mango Juice', 'PET Bottles', 12.3, 'Breakage during filling', now() - interval '4 days', gen_random_uuid()),
  ('Juice Bottling Line A', 'Pineapple Juice', 'Pineapple Concentrate', 28.0, 'Spillage during transfer', now() - interval '6 days', gen_random_uuid()),
  ('Juice Bottling Line A', 'Pineapple Juice', 'Bottle Caps', 3.5, 'Mis-feed on capper', now() - interval '8 days', gen_random_uuid()),
  ('Dairy Packaged Foods Unit 1', 'Yoghurt', 'Milk Base', 62.0, 'Temperature excursion', now() - interval '3 days', gen_random_uuid()),
  ('Dairy Packaged Foods Unit 1', 'Yoghurt', 'Cultures', 1.2, 'Batch contamination discard', now() - interval '7 days', gen_random_uuid()),
  ('Dairy Packaged Foods Unit 1', 'Yoghurt', 'Packaging Cups', 8.7, 'Seal failures', now() - interval '10 days', gen_random_uuid()),
  ('Pineapple Processing Line B', 'Pineapple Juice', 'Fresh Pineapple', 78.5, 'Spoilage - overripe fruit', now() - interval '1 day', gen_random_uuid()),
  ('Pineapple Processing Line B', 'Pineapple Juice', 'Concentrate', 15.8, 'Equipment flush - cleaning', now() - interval '5 days', gen_random_uuid()),
  ('Pineapple Processing Line B', 'Pineapple Juice', 'Cartons', 5.2, 'Printer alignment waste', now() - interval '9 days', gen_random_uuid()),
  ('Mixed Fruit Beverage Line C', 'Mixed Fruit', 'Apple Concentrate', 32.0, 'Batch imbalance correction', now() - interval '3 days', gen_random_uuid()),
  ('Mixed Fruit Beverage Line C', 'Mixed Fruit', 'Orange Pulp', 18.5, 'Transfer line spillage', now() - interval '8 days', gen_random_uuid()),
  ('Mixed Fruit Beverage Line C', 'Mixed Fruit', 'Glass Bottles', 22.0, 'Breakage during pasteurization', now() - interval '12 days', gen_random_uuid()),
  ('Mango Juice Extraction Unit', 'Mango Juice', 'Raw Mangoes', 120.0, 'Sorting rejects', now() - interval '2 days', gen_random_uuid()),
  ('Mango Juice Extraction Unit', 'Mango Juice', 'Fiber Residue', 85.0, 'Normal process waste', now() - interval '5 days', gen_random_uuid()),
  ('Water Bottling Line D', 'Water', 'PET Bottles', 18.5, 'Blow molding rejects', now() - interval '4 days', gen_random_uuid()),
  ('Water Bottling Line D', 'Water', 'Preforms', 8.0, 'Heating chamber faults', now() - interval '11 days', gen_random_uuid()),
  ('Water Bottling Line D', 'Water', 'Labels', 2.5, 'Print registration errors', now() - interval '14 days', gen_random_uuid());

-- Operator daily metrics (no rankings or scores - only objective data)
INSERT INTO operator_metrics_daily (operator_id, operator_name, snapshot_date, tasks_completed, tasks_assigned, avg_task_duration_minutes, total_downtime_caused_minutes, faults_logged, minor_faults, critical_faults, primary_line) VALUES
  (gen_random_uuid(), 'Wasswa Job', current_date - interval '1 day', 8, 8, 42.5, 0, 2, 2, 0, 'Juice Bottling Line A'),
  (gen_random_uuid(), 'Wasswa Job', current_date - interval '2 days', 7, 8, 45.0, 15, 1, 1, 0, 'Juice Bottling Line A'),
  (gen_random_uuid(), 'Nakato Grace', current_date - interval '1 day', 6, 7, 48.3, 10, 1, 1, 0, 'Dairy Packaged Foods Unit 1'),
  (gen_random_uuid(), 'Nakato Grace', current_date - interval '2 days', 9, 9, 38.5, 0, 0, 0, 0, 'Dairy Packaged Foods Unit 1'),
  (gen_random_uuid(), 'Okello David', current_date - interval '1 day', 5, 6, 55.0, 30, 3, 1, 2, 'Pineapple Processing Line B'),
  (gen_random_uuid(), 'Okello David', current_date - interval '2 days', 7, 7, 44.2, 5, 1, 1, 0, 'Pineapple Processing Line B'),
  (gen_random_uuid(), 'Nankinga Sarah', current_date - interval '1 day', 8, 8, 40.0, 0, 2, 2, 0, 'Mixed Fruit Beverage Line C'),
  (gen_random_uuid(), 'Nankinga Sarah', current_date - interval '2 days', 10, 10, 35.5, 0, 1, 1, 0, 'Mixed Fruit Beverage Line C'),
  (gen_random_uuid(), 'Kato Peter', current_date - interval '1 day', 4, 5, 62.5, 20, 2, 2, 0, 'Mango Juice Extraction Unit'),
  (gen_random_uuid(), 'Kato Peter', current_date - interval '2 days', 6, 6, 50.0, 0, 1, 1, 0, 'Mango Juice Extraction Unit'),
  (gen_random_uuid(), 'Auma Lydia', current_date - interval '1 day', 7, 7, 42.8, 0, 1, 1, 0, 'Water Bottling Line D'),
  (gen_random_uuid(), 'Auma Lydia', current_date - interval '2 days', 8, 8, 41.2, 10, 2, 2, 0, 'Water Bottling Line D'),
  (gen_random_uuid(), 'Ssentongo Mark', current_date - interval '1 day', 6, 6, 46.7, 5, 1, 1, 0, 'Juice Bottling Line A'),
  (gen_random_uuid(), 'Ssentongo Mark', current_date - interval '2 days', 7, 8, 44.0, 15, 2, 1, 1, 'Juice Bottling Line A'),
  (gen_random_uuid(), 'Babirye Janet', current_date - interval '1 day', 9, 9, 38.0, 0, 1, 1, 0, 'Dairy Packaged Foods Unit 1'),
  (gen_random_uuid(), 'Babirye Janet', current_date - interval '2 days', 8, 8, 42.5, 5, 1, 1, 0, 'Dairy Packaged Foods Unit 1');

-- Job stage analytics (historical completed jobs)
INSERT INTO job_stage_analytics (job_id, job_name, product_name, stage_order, stage_name, estimated_duration_minutes, actual_duration_minutes, started_at, completed_at, status, operator_name) VALUES
  ('JOB-301', 'Mango Juice Batch A-45', 'Mango Juice 500ml', 1, 'Raw Material Sorting', 30, 28, now() - interval '15 days', now() - interval '15 days' + interval '28 minutes', 'completed', 'Kato Peter'),
  ('JOB-301', 'Mango Juice Batch A-45', 'Mango Juice 500ml', 2, 'Washing & Preparation', 25, 30, now() - interval '15 days' + interval '30 minutes', now() - interval '15 days' + interval '60 minutes', 'completed', 'Nakato Grace'),
  ('JOB-301', 'Mango Juice Batch A-45', 'Mango Juice 500ml', 3, 'Extraction & Pulping', 60, 55, now() - interval '15 days' + interval '65 minutes', now() - interval '15 days' + interval '120 minutes', 'completed', 'Wasswa Job'),
  ('JOB-301', 'Mango Juice Batch A-45', 'Mango Juice 500ml', 4, 'Pasteurization', 90, 95, now() - interval '15 days' + interval '130 minutes', now() - interval '15 days' + interval '225 minutes', 'completed', 'Okello David'),
  ('JOB-301', 'Mango Juice Batch A-45', 'Mango Juice 500ml', 5, 'Filling', 45, 42, now() - interval '15 days' + interval '230 minutes', now() - interval '15 days' + interval '272 minutes', 'completed', 'Nankinga Sarah'),
  ('JOB-301', 'Mango Juice Batch A-45', 'Mango Juice 500ml', 6, 'Labeling & Packaging', 30, 35, now() - interval '15 days' + interval '275 minutes', now() - interval '15 days' + interval '310 minutes', 'completed', 'Auma Lydia'),
  ('JOB-302', 'Pineapple Juice Batch B-12', 'Pineapple Juice 1L', 1, 'Raw Material Sorting', 35, 40, now() - interval '12 days', now() - interval '12 days' + interval '40 minutes', 'completed', 'Ssentongo Mark'),
  ('JOB-302', 'Pineapple Juice Batch B-12', 'Pineapple Juice 1L', 2, 'Washing & Preparation', 25, 25, now() - interval '12 days' + interval '45 minutes', now() - interval '12 days' + interval '70 minutes', 'completed', 'Kato Peter'),
  ('JOB-302', 'Pineapple Juice Batch B-12', 'Pineapple Juice 1L', 3, 'Extraction & Pulping', 70, 85, now() - interval '12 days' + interval '80 minutes', now() - interval '12 days' + interval '165 minutes', 'completed', 'Babirye Janet'),
  ('JOB-302', 'Pineapple Juice Batch B-12', 'Pineapple Juice 1L', 4, 'Pasteurization', 90, 88, now() - interval '12 days' + interval '170 minutes', now() - interval '12 days' + interval '258 minutes', 'completed', 'Wasswa Job'),
  ('JOB-302', 'Pineapple Juice Batch B-12', 'Pineapple Juice 1L', 5, 'Filling', 50, 48, now() - interval '12 days' + interval '260 minutes', now() - interval '12 days' + interval '308 minutes', 'completed', 'Nakato Grace'),
  ('JOB-302', 'Pineapple Juice Batch B-12', 'Pineapple Juice 1L', 6, 'Labeling & Packaging', 35, 38, now() - interval '12 days' + interval '315 minutes', now() - interval '12 days' + interval '353 minutes', 'completed', 'Okello David'),
  ('JOB-303', 'Mixed Fruit Batch C-08', 'Mixed Fruit 250ml', 1, 'Ingredient Mixing', 45, 50, now() - interval '10 days', now() - interval '10 days' + interval '50 minutes', 'completed', 'Nankinga Sarah'),
  ('JOB-303', 'Mixed Fruit Batch C-08', 'Mixed Fruit 250ml', 2, 'Pasteurization', 90, 120, now() - interval '10 days' + interval '55 minutes', now() - interval '10 days' + interval '175 minutes', 'completed', 'Wasswa Job'),
  ('JOB-303', 'Mixed Fruit Batch C-08', 'Mixed Fruit 250ml', 3, 'Homogenization', 30, 28, now() - interval '10 days' + interval '180 minutes', now() - interval '10 days' + interval '208 minutes', 'completed', 'Nakato Grace'),
  ('JOB-303', 'Mixed Fruit Batch C-08', 'Mixed Fruit 250ml', 4, 'Filling', 55, 52, now() - interval '10 days' + interval '210 minutes', now() - interval '10 days' + interval '262 minutes', 'completed', 'Kato Peter'),
  ('JOB-303', 'Mixed Fruit Batch C-08', 'Mixed Fruit 250ml', 5, 'QC Check', 20, 25, now() - interval '10 days' + interval '270 minutes', now() - interval '10 days' + interval '295 minutes', 'completed', 'Ssentongo Mark'),
  ('JOB-304', 'Dairy Yoghurt Batch D-22', 'Yoghurt Cups', 1, 'Milk Reception', 20, 18, now() - interval '8 days', now() - interval '8 days' + interval '18 minutes', 'completed', 'Auma Lydia'),
  ('JOB-304', 'Dairy Yoghurt Batch D-22', 'Yoghurt Cups', 2, 'Pasteurization', 45, 50, now() - interval '8 days' + interval '25 minutes', now() - interval '8 days' + interval '75 minutes', 'completed', 'Babirye Janet'),
  ('JOB-304', 'Dairy Yoghurt Batch D-22', 'Yoghurt Cups', 3, 'Culturing', 180, 200, now() - interval '8 days' + interval '80 minutes', now() - interval '8 days' + interval '280 minutes', 'completed', 'Okello David'),
  ('JOB-304', 'Dairy Yoghurt Batch D-22', 'Yoghurt Cups', 4, 'Filling & Sealing', 40, 38, now() - interval '8 days' + interval '290 minutes', now() - interval '8 days' + interval '328 minutes', 'completed', 'Nankinga Sarah'),
  ('JOB-304', 'Dairy Yoghurt Batch D-22', 'Yoghurt Cups', 5, 'Cooling & Storage', 30, 35, now() - interval '8 days' + interval '335 minutes', now() - interval '8 days' + interval '370 minutes', 'completed', 'Wasswa Job'),
  ('JOB-305', 'Mango Juice Batch A-46', 'Mango Juice 500ml', 1, 'Raw Material Sorting', 30, NULL, now() - interval '5 days', NULL, 'cancelled', 'Kato Peter'),
  ('JOB-305', 'Mango Juice Batch A-46', 'Mango Juice 500ml', 2, 'Washing & Preparation', 25, NULL, NULL, NULL, 'cancelled', NULL),
  ('JOB-306', 'Water Bottling Batch E-33', 'Water 500ml', 1, 'Filtration', 25, 22, now() - interval '3 days', now() - interval '3 days' + interval '22 minutes', 'completed', 'Auma Lydia'),
  ('JOB-306', 'Water Bottling Batch E-33', 'Water 500ml', 2, 'Ozonation', 15, 15, now() - interval '3 days' + interval '25 minutes', now() - interval '3 days' + interval '40 minutes', 'completed', 'Ssentongo Mark'),
  ('JOB-306', 'Water Bottling Batch E-33', 'Water 500ml', 3, 'Bottling', 60, 58, now() - interval '3 days' + interval '50 minutes', now() - interval '3 days' + interval '108 minutes', 'completed', 'Babirye Janet'),
  ('JOB-306', 'Water Bottling Batch E-33', 'Water 500ml', 4, 'Labeling', 25, 28, now() - interval '3 days' + interval '115 minutes', now() - interval '3 days' + interval '143 minutes', 'completed', 'Nakato Grace');